### ISSUE TITLE
failed to save video

### ISSUE THREAD

**Issue by zhangjian94cn** [huggingface/huggingface_sb3#28]
when running `package_to_hub` function, I found the following error:

```bash
Exception ignored in: <function VecVideoRecorder.__del__ at 0x7f8db5c58e50>
Traceback (most recent call last):
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 113, in __del__
    self.close_video_recorder()
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 104, in close_video_recorder
    self.video_recorder.close()
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/gymnasium/wrappers/monitoring/video_recorder.py", line 161, in close
    clip.write_videofile(self.path, logger=moviepy_logger)
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    for i, extra in enumerate(extras):
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    for i, extra in enumerate(extras):
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    for i, extra in enumerate(extras):
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 213, in ffmpeg_write_video
    with FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
  File "/home/zhangjian/miniconda3/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 88, in __init__
    '-r', '%.02f' % fps,
TypeError: must be real number, not NoneType
```
The python code is shown as below:
```py
import gymnasium as gym

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.env_util import make_vec_env

from huggingface_sb3 import package_to_hub

# PLACE the variables you've just defined two cells above
# Define the name of the environment
env_id = "LunarLander-v2"

# TODO: Define the model architecture we used
model_architecture = "PPO"

## Define a repo_id
## repo_id is the id of the model repository from the Hugging Face Hub (repo_id = {organization}/{repo_name} for instance ThomasSimonini/ppo-LunarLander-v2
## CHANGE WITH YOUR REPO ID
repo_id = "zhangjian94cn/ppo-LunarLander-v2" # Change with your repo id, you can't push with mine 😄

## Define the commit message
commit_message = "Upload PPO LunarLander-v2 trained agent"

# Create the evaluation env and set the render_mode="rgb_array"
eval_env = DummyVecEnv([lambda: gym.make(env_id, render_mode="rgb_array")])

# PLACE the package_to_hub function you've just filled here
package_to_hub(model=model, # Our trained model
               model_name=model_name, # The name of our trained model 
               model_architecture=model_architecture, # The model architecture we used: in our case PPO
               env_id=env_id, # Name of the environment
               eval_env=eval_env, # Evaluation Environment
               repo_id=repo_id, # id of the model repository from the Hugging Face Hub (repo_id = {organization}/{repo_name} for instance ThomasSimonini/ppo-LunarLander-v2
               commit_message=commit_message)
```

**Comment by simoninithomas** [comment]
Hey there 👋 
1. Can you check which version of huggingface_sb3 you use and update to 2.2.5?
2. What did you put to model_name? Sometimes that kind of bug happens because the variables were mixed

**Comment by zhangjian94cn** [comment]
@simoninithomas Thanks for your response! I have found the solution [here](https://stackoverflow.com/questions/68032884/getting-typeerror-must-be-real-number-not-nonetype-whenever-trying-to-run-wr). It is a bug from moviepy.
